# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Proposal content in markdown/HTML format')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether this proposal was AI-generated')),
                ('ai_model_used', models.CharField(blank=True, help_text="AI model used for generation (e.g., 'watsonx.ai/granite-13b')", max_length=100)),
                ('generation_metadata', models.JSONField(blank=True, help_text='Metadata about AI generation (tokens used, confidence, etc.)', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When proposal was submitted', null=True)),
                ('submission_method', models.CharField(blank=True, help_text="How proposal was submitted (e.g., 'email', 'portal')", max_length=100)),
                ('version', models.IntegerField(default=1, help_text='Version number of this proposal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(help_text='Grant this proposal is for', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='grants.grant')),
                ('organization', models.ForeignKey(help_text='Organization submitting the proposal', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='organizations.organization')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Previous version of this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'db_table': 'proposals',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='proposals_organiz_bf2472_idx'), models.Index(fields=['grant', 'status'], name='proposals_grant_i_5e40cf_idx'), models.Index(fields=['created_at'], name='proposals_created_9ae4ff_idx'), models.Index(fields=['status'], name='proposals_status_6b8498_idx')],
            },
        ),
    ]
