# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('grant_match', 'Grant Match'), ('application_status', 'Application Status'), ('proposal_update', 'Proposal Update'), ('deadline_reminder', 'Deadline Reminder'), ('system_announcement', 'System Announcement')], db_index=True, help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
