# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_application',
            field=models.ForeignKey(blank=True, help_text='Related application if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='grants.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_grant',
            field=models.ForeignKey(blank=True, help_text='Related grant if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='grants.grant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_proposal',
            field=models.ForeignKey(blank=True, help_text='Related proposal if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notification_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notification_type_created_idx'),
        ),
    ]
