# Generated by Django 4.2.7 on 2026-05-03 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(db_index=True, help_text='AI-calculated match score between 0 and 100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('match_reasons', models.JSONField(default=list, help_text='List of reasons why this grant matches the organization')),
                ('recommended_actions', models.JSONField(default=list, help_text='List of recommended next steps for the organization')),
                ('algorithm_version', models.CharField(help_text='Version of the matching algorithm used', max_length=50)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False, help_text='Whether the user has dismissed this match')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='When the match was dismissed', null=True)),
                ('dismissed_reason', models.TextField(blank=True, help_text='Optional reason for dismissing the match')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(help_text='Grant that was matched to the organization', on_delete=django.db.models.deletion.CASCADE, related_name='organization_matches', to='grants.grant')),
                ('organization', models.ForeignKey(help_text='Organization for which this match was generated', on_delete=django.db.models.deletion.CASCADE, related_name='grant_matches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Grant Match',
                'verbose_name_plural': 'Grant Matches',
                'db_table': 'grant_matches',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'grant'], name='grantmatch_org_grant_idx'), models.Index(fields=['organization', '-match_score'], name='grantmatch_org_score_idx'), models.Index(fields=['grant', '-match_score'], name='grantmatch_grant_score_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='grantmatch',
            constraint=models.UniqueConstraint(fields=('organization', 'grant'), name='unique_organization_grant_match'),
        ),
    ]
