# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(default='501(c)(3) Nonprofit', max_length=100)),
                ('ein', models.CharField(blank=True, help_text='Employer Identification Number', max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('mission', models.TextField(help_text="Organization's mission statement")),
                ('description', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of organizational goals')),
                ('categories', models.JSONField(blank=True, default=list, help_text="Nonprofit categories/focus areas (e.g., ['education', 'health', 'environment'])")),
                ('historical_projects', models.JSONField(blank=True, default=list, help_text='Past projects and achievements')),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Annual operating budget in USD', max_digits=12, null=True)),
                ('funding_needs', models.DecimalField(decimal_places=2, default=0, help_text='Current funding needs in USD', max_digits=12)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether organization has been verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector embedding for AI-powered matching', null=True)),
                ('last_embedding_update', models.DateTimeField(blank=True, help_text='When the embedding was last updated', null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'), models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx'), models.Index(fields=['is_verified'], name='organizatio_is_veri_831d59_idx')],
            },
        ),
    ]
