# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('organization', models.CharField(help_text='Funding organization name', max_length=255)),
                ('funding_amount', models.DecimalField(decimal_places=2, help_text='Total funding amount available', max_digits=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum funding amount', max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum funding amount', max_digits=12, null=True)),
                ('description', models.TextField(help_text='Detailed grant description')),
                ('requirements', models.TextField(help_text='Grant requirements and criteria')),
                ('eligibility', models.JSONField(blank=True, default=list, help_text='List of eligibility criteria')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Grant tags/keywords for filtering')),
                ('categories', models.JSONField(blank=True, default=list, help_text="Grant categories (e.g., ['education', 'health'])")),
                ('deadline', models.DateTimeField(db_index=True, help_text='Application deadline')),
                ('announcement_date', models.DateTimeField(blank=True, help_text='When grant was announced', null=True)),
                ('award_date', models.DateTimeField(blank=True, help_text='Expected award date', null=True)),
                ('source', models.CharField(help_text='Source of grant (e.g., grants.gov, foundation website)', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='URL to original grant posting')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External identifier from source system', max_length=255)),
                ('status', models.CharField(choices=[('opportunity', 'Opportunity'), ('reviewing', 'Reviewing'), ('drafting', 'Drafting'), ('submitted', 'Submitted')], db_index=True, default='opportunity', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether grant is currently accepting applications')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector embedding for AI-powered matching', null=True)),
                ('last_embedding_update', models.DateTimeField(blank=True, help_text='When the embedding was last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'db_table': 'grants',
                'ordering': ['-deadline'],
                'indexes': [models.Index(fields=['deadline', 'is_active'], name='grants_deadlin_d6bde9_idx'), models.Index(fields=['funding_amount'], name='grants_funding_2c24dd_idx'), models.Index(fields=['created_at'], name='grants_created_b75c06_idx'), models.Index(fields=['status'], name='grants_status_de9c13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('submitted_date', models.DateTimeField(blank=True, help_text='When application was submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.grant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
