# Generated by Django 4.2.7 on 2026-05-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='proposals.proposal'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'status'], name='application_organiz_01d488_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['grant', 'status'], name='application_grant_i_881bff_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_a07231_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('grant', 'organization')},
        ),
    ]
