# Generated by Django 4.2.7 on 2026-05-03 00:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('grants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='organization',
            new_name='funder_name',
        ),
        migrations.AddField(
            model_name='grant',
            name='application_url',
            field=models.URLField(blank=True, help_text='URL to apply for the grant'),
        ),
        migrations.AddField(
            model_name='grant',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='grant',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list, help_text="List of focus areas (e.g., ['education', 'healthcare'])"),
        ),
        migrations.AddField(
            model_name='grant',
            name='funder_website',
            field=models.URLField(blank=True, help_text="Funder's website"),
        ),
        migrations.AddField(
            model_name='grant',
            name='geographic_scope',
            field=models.CharField(blank=True, help_text="Geographic scope (e.g., 'National', 'Regional', 'Global')", max_length=100),
        ),
        migrations.CreateModel(
            name='SavedGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Notes about why this grant is interesting')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='grants.grant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_grants', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Saved Grant',
                'verbose_name_plural': 'Saved Grants',
                'db_table': 'saved_grants',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['organization', '-saved_at'], name='saved_grant_organiz_ccbbd3_idx')],
                'unique_together': {('organization', 'grant')},
            },
        ),
    ]
